### ISSUE TITLE
Implement Repository Fetch / Update process

### ISSUE THREAD

**Issue by dharma-guardian** [secure-software-engineering/rose#128]
* [x] Redefine repository structure in https://github.com/secure-software-engineering/rose/blob/master/docs/repository.md
* [x] update observers/extractors with higher version numbers 
* [x] store/fetch network identifiers in storage/repository
* [x] verification
* [x] auto update

**Comment by iamolivinius** [comment]
What should happen if a verification fails?

[ ] stopUpdateProcess && logErrorMessage
[ ] proceedUpdateProcess && logErrorMessage

**Comment by apoller** [comment]
For security reasons the update process has to stop. But we could add a "check repository signature" radio button to the settings page, which should be "on" by default.

**Comment by dharma-guardian** [comment]
@iamolivinius  Also, hab mal folgendes probiert. Und da du auf Fehlersuchen stehst...

```Javascript
    let baseConf = $.get(configs.get('repositoryURL'));
    let sig = $.get(configs.get('repositoryURL') + '.asc');
    let key = $.get('https://secure-software-engineering.github.io/rose/example/' + 'public.key');

    $.when(baseConf, sig, key).done(function (confData, sigData, keyData) {

      verify(confData, sigData, keyData).then(function(fingerprint) {
        debugger;
      }, function(value) {
        // failure
        debugger
      });
  });
```

Aber erhalte folgenden Fehler in `value` beim zweiten `debugger` statement. Die Requests funktionieren; also es werden sinnvolle Daten übergeben.

```
TypeError: this.data.split is not a function
at Parser.exports.Parser.Parser.init (chrome-extension://oppgjcbbpcklpbkpbmgkbdneabdffhgj/backgroundscript.js:53914:30)
at Parser (chrome-extension://oppgjcbbpcklpbkpbmgkbdneabdffhgj/backgroundscript.js:53909:12)
at new Parser (chrome-extension://oppgjcbbpcklpbkpbmgkbdneabdffhgj/backgroundscript.js:36476:43)
at chrome-extension://oppgjcbbpcklpbkpbmgkbdneabdffhgj/backgroundscript.js:36514:15
at exports.katch.katch (chrome-extension://oppgjcbbpcklpbkpbmgkbdneabdffhgj/backgroundscript.js:54400:13)
at exports.decode.decode (chrome-extension://oppgjcbbpcklpbkpbmgkbdneabdffhgj/backgroundscript.js:36513:12)
at KeyManager.import_from_armored_pgp (chrome-extension://oppgjcbbpcklpbkpbmgkbdneabdffhgj/backgroundscript.js:40142:17)
at lib$rsvp$node$$tryApply (chrome-extension://oppgjcbbpcklpbkpbmgkbdneabdffhgj/backgroundscript.js:65698:11)
at lib$rsvp$node$$handleValueInput (chrome-extension://oppgjcbbpcklpbkpbmgkbdneabdffhgj/backgroundscript.js:65798:20)
at fn (chrome-extension://oppgjcbbpcklpbkpbmgkbdneabdffhgj/backgroundscript.js:65786:18)
```

hf 
![Adventure Time Gif glasses](http://i.giphy.com/KI9oNS4JBemyI.gif)

**Comment by iamolivinius** [comment]
That's the point where u wanna have a compiler that does type checking for you :smile: 

The signature of the verify function is: 

```js
function verify(data: string, signature: string, key: string): Promise {}
```

You're calling `verify` with 3 arrays

![screenshot from 2015-09-17 22 33 02](https://cloud.githubusercontent.com/assets/832245/9945340/03dac3a0-5d8d-11e5-842b-089453983b4a.png)

**Comment by dharma-guardian** [comment]
OK, it works. I'm currently rewriting the update process.

**Comment by dharma-guardian** [comment]
@iamolivinius In the current state of master branch the update does not work. The observers are not updated.

**Comment by iamolivinius** [comment]
Obviously

**Comment by dharma-guardian** [comment]
So, you are working on it?

**Comment by dharma-guardian** [comment]
What's crackin'?
