### ISSUE TITLE
Update devDependencies

### ISSUE THREAD

**Issue by dharma-guardian** [secure-software-engineering/rose#150]
This is not green enough! 
[![devDependency Status](https://david-dm.org/secure-software-engineering/rose/dev-status.svg)](https://david-dm.org/secure-software-engineering/rose#info=devDependencies)

**Comment by iamolivinius** [comment]
Your weapon of choice will be: npm-check-updates
Am 04.08.2015 6:36 nachm. schrieb "Felix" <notifications@github.com>:

**Comment by iamolivinius** [comment]
Upgrading devDependencies has breaking changes. At this point its is neither necessary nor recommended. Closing this ticket - at least for the actual milestone.

**Comment by dharma-guardian** [comment]
A quick test with `ncu`:

```
$  ncu -u

 babel               ^5.4.7  →  ^6.0.15 
 babelify            ^6.1.2  →   ^7.2.0 
 browserify          ^9.0.3  →  ^12.0.1 
 del                 ^1.1.1  →   ^2.0.2 
 gulp-autoprefixer   ^2.1.0  →   ^3.1.0 
 gulp-filter         ^2.0.2  →   ^3.0.1 
 gulp-flatten         0.0.4  →    0.2.0 
 gulp-if             ^1.2.5  →   ^2.0.0 
 gulp-minify-css     ^0.5.1  →   ^1.2.1 
 gulp-plumber        ^0.6.6  →   ^1.0.1 
 gulp-print          ^1.1.0  →   ^2.0.1 
 semantic-ui        ^1.12.2  →   ^2.1.5 
 watchify            ^2.4.0  →   ^3.6.0 
```
broke the build process. Seems to be `browserify`:
```
$ gulp
[14:33:49] Using gulpfile ~/Dokumente/Dipo/rose/gulpfile.js
[14:33:49] Starting 'clean:dist'...
[14:33:49] Starting 'clean:tmp'...
[14:33:49] Starting 'connect'...
[14:33:49] Finished 'connect' after 7.61 ms
[14:33:49] Server started http://localhost:8080
[14:33:49] LiveReload started on port 35729
[14:33:49] Finished 'clean:dist' after 17 ms
[14:33:49] Finished 'clean:tmp' after 21 ms
[14:33:49] Starting 'default'...
[14:33:49] Starting 'watch'...
[14:33:50] Finished 'watch' after 801 ms
[14:33:50] Starting 'build:backgroundscript'...
[14:33:50] Starting 'build:contentscript'...
[14:33:50] Starting 'build:manifest'...
[14:33:50] Starting 'copy:bowerFiles'...
[14:33:50] Starting 'copy:staticFiles'...
[14:33:50] Finished 'default' after 854 ms
[14:33:50] Finished 'build:manifest' after 73 ms
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: Cannot find module '/home/fepp/Dokumente/Dipo/rose/content_app.js' from '/home/fepp/Dokumente/Dipo/rose'
    at /home/fepp/Dokumente/Dipo/rose/node_modules/browserify/node_modules/resolve/lib/async.js:55:21
    at load (/home/fepp/Dokumente/Dipo/rose/node_modules/browserify/node_modules/resolve/lib/async.js:69:43)
    at onex (/home/fepp/Dokumente/Dipo/rose/node_modules/browserify/node_modules/resolve/lib/async.js:92:31)
    at /home/fepp/Dokumente/Dipo/rose/node_modules/browserify/node_modules/resolve/lib/async.js:22:47
    at FSReqWrap.oncomplete (fs.js:82:15)
```
